# name: Deploy cicd-linode to Linode with Docker

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Modify /etc/hosts
#         run: |
#           echo "172.232.217.78:5000 registry-1.docker.io" | sudo tee -a /etc/hosts
#           cat /etc/hosts

#       - name: Build Docker Image
#         run: |
#           docker build -t cicd-linode:latest .
#           docker tag cicd-linode:latest 172.232.217.78:5000/cicd-linode:latest

#       - name: Log in to Docker registry
#         run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

#       - name: Push Docker Image to Remote Registry
#         run: docker push 172.232.217.78:5000/cicd-linode:latest

#       - name: Deploy to Linode
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: '22'
#           script: |
#             docker pull hub.docker.com/cicd-linode:latest
#             docker stop cicd-linode || true
#             docker rm cicd-linode || true
#             docker run -d --name cicd-linode -p 80:80 172.234.63.107/cicd-linode:latest

#////////////////////////////////////////////////////////////////

# name: CI/CD Pipeline

# on:
#   push:
#     branches: [main]

# jobs:
#   build-push-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check Out Repo
#         uses: actions/checkout@v2

#       - name: Log in to Private Docker Registry
#         run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login 172.232.217.78 --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

#       - name: Build and Push Docker Image
#         run: |
#           docker build -t 172.232.217.78/cicd-linode:latest .
#           docker push 172.232.217.78/cicd-linode:latest

#       - name: SSH and Deploy on Server
#         uses: appleboy/ssh-action@master
#         with:
#           host: 172.234.63.107
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             docker pull 172.232.217.78/cicd-linode:latest
#             docker stop cicd-linode || true
#             docker rm cicd-linode || true
#             docker run -d --name cicd-linode -p externalPort:internalPort 172.232.217.78/cicd-linode:latest

name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/cicd-linode:v1 .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/cicd-linode:v1

      - name: SSH and Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker pull ghcr.io/${{ github.repository }}/cicd-linode:v1
            docker stop cicd-linode || true
            docker rm cicd-linode || true
            docker run -d --name cicd-linode ghcr.io/${{ github.repository }}/cicd-linode:v1
