# name: Deploy to Linode

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Deploy to Linode
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: '22'
#           source: 'dist/*'
#           target: '/var/www/cicd-test-linode'
#

name: Deploy cicd-linode to Linode with Docker

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t cicd-linode:latest .
          docker tag cicd-linode:latest 172.232.217.78/cicd-linode:latest

      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login 172.232.217.78 --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image to Remote Registry
        run: docker push 172.232.217.78/cicd-linode:latest

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: '22'
          script: |
            docker pull 172.232.217.78/cicd-linode:latest
            docker stop cicd-linode || true
            docker rm cicd-linode || true
            docker run -d --name cicd-linode -p 80:80 172.234.63.107/cicd-linode:latest
