name: Deploy cicd-linode to Linode with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Modify /etc/hosts
        run: |
          echo "172.232.217.78 registry-1.docker.io" | sudo tee -a /etc/hosts
          cat /etc/hosts

      - name: Build Docker Image
        run: |
          docker build -t cicd-linode:latest .
        # docker tag cicd-linode:latest 172.232.217.78/cicd-linode:latest

      - name: Log in to Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Push Docker Image to Remote Registry
        run: docker push 172.232.217.78/cicd-linode:latest

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: '22'
          script: |
            docker pull hub.docker.com/cicd-linode:latest
            docker stop cicd-linode || true
            docker rm cicd-linode || true
            docker run -d --name cicd-linode -p 80:80 172.234.63.107/cicd-linode:latest
